node{
    stage('Clone repository'){
        checkout scm
        sh 'echo Repository cloned'
    }
    stage('Building app'){
        app = docker.build("jakubnajman/blog_app","-f blog/Dockerfile .")
        sh 'echo App builded.'
    }
    stage('Pushing to Azure registry'){
        sh 'docker tag jakubnajman/blog_app yndblog.azurecr.io/blog_app'
        sh 'docker push yndblog.azurecr.io/blog_app'
    }
    // stage('Pulling on Minikube Docker.'){
    //     sh 'minikube ssh'
    //     sh 'doker pull jakubnajman/'
    // }
    stage('Test image'){
        sh 'echo Test passed.'
    }
    stage('Deploying on Kubernetes'){
        sh 'eval $(minikube docker-env)'
        withCredentials([azureAuth(credentialsId: credsId, AZUREHUB:'yndblog.azurecr.io/blog_app' ,AZUREID: 'yndblog', AZUREPASSWORD: 'LT6qcAlPKU+mJnkAkvYJj15L/PtaZioy')]){
            sh 'docker login $azureHub --username=$ASUREID --password=$AZUREPASSWORD'
        }
        sh 'cd blog && kubectl apply -f kube/'
        sh 'echo Deployments and services aplied.'
    }
    // stage('Starting services'){
    //     sh 'minikube service postgresql-service &'
    //     sh 'minikube service blog-service &'
    // }
}