apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: "090660780783.dkr.ecr.eu-central-1.amazonaws.com/blog:$VERSION"
        imagePullPolicy: Always
        env:
        - name: DATABASE_HOST
          value: $DATABASE_HOST
        - name: DATABASE_NAME
          value: $DATABASE_NAME
        - name: DATABASE_PASSWORD
          value: $DATABASE_PASSWORD
        - name: DATABASE_USERNAME
          value: $DATABASE_USERNAME
        - name: REDIS_URI
          value: $REDIS_URI
        ports:
          - containerPort: 3000