node() {
    def myImage
    stage("git") {
        git 'https://github.com/mparadowsky/devops-exercise'
    }
    stage("Building image") {
        myImage = docker.build("mparadowsky/blog", "./blog")
    }
    stage("Pushing image to docker hub") {
        myImage.push("")
    }
     stage("Clearing pods and deployments") {
        sh 'kubectl delete deployment/blog'
        sh 'kubectl delete deployment/database'
    }
    stage("Launching new deployments") {
        sh 'kubectl apply -f blog/kubernetes'
    }
    
}