node { 
 /*   checkout scm
    def testImage = docker.build("blog", "blog/") 
    
    testImage.inside {
        sh 'make test'
    }
    /*    stage('Build') { 
        sh 'docker build -t blog .'
         
    }
    stage('Test') { 
       echo 'BBB'
    }
    stage('Deploy') { 
        echo'111'
    } */

    def app

    stage('Clone repository') {
        checkout scm
    }

    stage('Build image') {
        //app = docker.build("blog_pipe", "-f blog/Dockerfile .")
        //sh 'ls'
        sh 'cd blog && docker-compose up --build --remove-orphans'
    }

    stage('Test image') {
        app.inside {
            sh 'echo "Tests passed"'
        }
    }
}